root: true
parser: "@typescript-eslint/parser"
extends:
  - plugin:prettier/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:@typescript-eslint/recommended
  - standard
plugins:
  - prettier
  - standard
  - typescript
rules:
  # ------------------------------------- Standard ESLint rules ------------------------------------
  quotes: [error, "double", { avoidEscape: true }]
  semi: [error, "never"]
  space-before-function-paren: [error, "always"]
  # ---------------------------------------- Prettier rules ----------------------------------------
  prettier/prettier: off
  # --------------------------------------- TypeScript rules ---------------------------------------
  "@typescript-eslint/explicit-function-return-type": off
